import { jsx as _jsx } from "react/jsx-runtime";
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./index.css";
import { ConnectionsProvider } from "./contexts/ConnectionsContext";
import { GroupsProvider } from "./contexts/GroupsContext";
import { EventProvider } from "./contexts/EventContext";
import { EventsProvider } from "./contexts/EventsContext";
import { UserProvider } from "./contexts/UserContext";
import { BrowserRouter } from "react-router-dom";
import { GroupProvider } from "./contexts/GroupContext";
import { ConnectionProvider } from "./contexts/ConnectionContext";
import { CreateGroupProvider } from "./contexts/CreateGroupContext";
import { CreateUserProvider } from "./contexts/CreateUserContext";
import { SignInProvider } from "./contexts/SignInContext";
import { ModalProvider } from "./contexts/ModalContext";
import { CreateEventProvider } from "./contexts/CreateEventContext";
import { EventModalProvider } from "./contexts/EventModelContext";
import { ScreenWidthProvider } from "./contexts/ScreenWidthContext";
const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(_jsx(React.StrictMode, { children: _jsx(BrowserRouter, { children: _jsx(ScreenWidthProvider, { children: _jsx(ModalProvider, { children: _jsx(EventsProvider, { children: _jsx(UserProvider, { children: _jsx(EventProvider, { children: _jsx(GroupsProvider, { children: _jsx(GroupProvider, { children: _jsx(ConnectionsProvider, { children: _jsx(ConnectionProvider, { children: _jsx(UserProvider, { children: _jsx(CreateGroupProvider, { children: _jsx(CreateEventProvider, { children: _jsx(CreateUserProvider, { children: _jsx(SignInProvider, { children: _jsx(EventModalProvider, { children: _jsx(App, {}) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }) }));
